GEM:
    X : 160   # Количество падов
    Y : 40
    call_period : 0.449  # период опросов детектора в секундах
data:
    hist_buffer_len : 256 # Кол-во хранимых срезов гистограммы пятна
    asym_buffer_len : 3276800 # Кол-во хранимых точек
web:
    port: 5006
    allowed_ip:
        - localhost
        - 192.168.163.79  # rokk1m
        - 192.168.176.61  # spin
        - 192.168.176.10  # pult6
        - 192.168.174.14  # kedr24
        - 192.168.174.80  # 256 кабинет
        - 192.168.176.20  # student room
