GEM:
    X : 160   # Количество падов
    Y : 40
    call_period : 1 # Период опросов детектора [с]
laser:
    freq : 1945.18764
depolarizer:
    bounds:  # Допустимые значения, устанавливаемые из веб-интерфейса
        speed: [-10, 10]
        step:  [0, 10000]
        initial: [0, 10000]
        final: [0, 10000]
        harmonic_number : [-20, 20]
        attenuation: [7, 60]
data:
    hist_buffer_len : 256 # Кол-во хранимых срезов гистограммы пятна
    asym_buffer_len : 864_000 # Кол-во хранимых точек
    delta_time : 0.1  # Время усреднения точек [с] # Разобраться с nan
    writing_delta_time : 10  # Период сохранения данных на диск [с]
web:
    port: 5006
    allowed_ip:
        - localhost
        - 192.168.163.79  # rokk1m
        - 192.168.176.61  # spin
        - 192.168.176.10  # pult6
        - 192.168.174.80  # 256 кабинет
        - 192.168.176.20  # student room
        - 192.168.174.20  # kedr-shift
        - 192.168.174.14  # kedr-24
        - 192.168.176.68  # l1-3-much
debug:
    GEM_idle : False # Использовать смоделированные данные вместо детектора
    read_hitdump : False  # читать hitdump
    hitdump_dir : ./data/hitdump
    hitdump_mask : full\.2017-05-13_0[4-9].* #  в формаре регулярного выражения